import type { Dish } from "@/types/dish.types";

export const dishesData: Dish[] = [
  {
    id: "dish_1",
    restaurant: "1708 Pizza di Napoli",
    name: "Pizza with Mortadella",
    rating: 4.2,
    description:
      "A Neapolitan-style pizza featuring tender mortadella and creamy tomato sauce. The combination of crispy crust, aromatic basil, and pistachios creates an unforgettable Italian taste experience.",
    weight: "346 g",
    price: 299,
    ingredients: [
      "creamy tomato sauce",
      "mozzarella",
      "mortadella",
      "cherry tomatoes",
      "basil cream cheese",
      "parmesan",
      "pistachios",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744832864/igtva20v6ayphymmi7ck.jpg",
    allergens: ["gluten", "milk", "nuts"],
    nutrition: {
      calories: 285,
      protein: 12,
      fat: 15,
      carbs: 28,
    },
    reviews: [
      {
        username: "Emma Wilson",
        rating: 4.5,
        text: "The mortadella pizza was absolutely divine! The combination of the crispy crust and tender mortadella created a perfect harmony of textures. The addition of pistachios added an unexpected but delightful crunch. Will definitely order again!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Michael Chen",
        rating: 4.0,
        text: "A unique take on pizza that really works. The basil cream cheese adds a lovely freshness, and the quality of the mortadella is excellent. The portion size is also quite generous.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sofia Garcia",
        rating: 4.2,
        text: "The pizza arrived hot and fresh. I particularly enjoyed how the flavors of the mortadella and pistachios complemented each other. The tomato sauce had just the right amount of tanginess.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_2",
    restaurant: "Respublica Sadu",
    name: "Beef Taco",
    rating: 4.5,
    description:
      "Juicy taco with tender beef and fresh vegetables under our signature Mary Rose sauce. A perfect blend of Mexican traditions with modern culinary trends.",
    weight: "420 g",
    price: 367,
    ingredients: [
      "tortilla",
      "shredded beef",
      "lettuce",
      "tomatoes",
      "onions",
      "Mary Rose sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744832900/x1bht2bn271w6d7ubu0c.jpg",
    allergens: ["gluten", "eggs", "mustard"],
    nutrition: {
      calories: 310,
      protein: 18,
      fat: 14,
      carbs: 32,
    },
    reviews: [
      {
        username: "David Thompson",
        rating: 4.8,
        text: "These tacos are incredible! The beef is perfectly seasoned and tender, and the Mary Rose sauce adds a unique twist that really works. The portion size is generous too.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Maria Rodriguez",
        rating: 4.3,
        text: "Love the fusion of flavors in these tacos. The vegetables are always fresh and crispy, and the beef is cooked to perfection. The sauce is a game-changer!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "James Wilson",
        rating: 4.4,
        text: "A fantastic twist on traditional tacos. The Mary Rose sauce is unique and delicious, and the quality of the ingredients is consistently high. Great value for money!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_3",
    restaurant: "Respublica Sadu",
    name: "Chicken Pancakes",
    rating: 4.1,
    description:
      "Fluffy pancakes with chicken and melted cheddar cheese under pesto sauce. The perfect breakfast that combines the tenderness of pancakes with juicy filling.",
    weight: "230 g",
    price: 255,
    ingredients: [
      "pancakes",
      "chicken",
      "cheddar cheese",
      "pesto sauce",
      "cherry tomatoes",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744832937/dvohl1kaq5oig6obpxhq.jpg",
    allergens: ["milk", "nuts (walnuts)", "gluten"],
    nutrition: {
      calories: 620,
      protein: 28,
      fat: 32,
      carbs: 50,
    },
    reviews: [
      {
        username: "Oliver Taylor",
        rating: 4.7,
        text: "These Chicken and Cheddar Pancakes are a game-changer for breakfast! The pancakes are incredibly fluffy, and the chicken is perfectly seasoned. The melted cheddar adds a rich, savory element that takes this dish to another level. The pesto sauce is a brilliant touch, adding freshness and complexity to every bite. The portion size is perfect for a hearty breakfast or brunch. Absolutely worth waking up early for!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Isabella Chen",
        rating: 4.3,
        text: "What an innovative take on traditional pancakes! The combination of savory chicken and sharp cheddar creates a perfect balance of flavors. The sun-dried tomatoes add a lovely burst of intensity, while the pesto brings everything together beautifully. The texture contrast between the fluffy pancakes and the tender chicken is spot-on. A bit rich for everyday breakfast, but perfect for special occasions.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Anderson",
        rating: 4.5,
        text: "I was initially skeptical about savory pancakes, but these have completely won me over! The chicken is moist and flavorful, the cheddar adds the perfect amount of sharpness, and the pesto sauce elevates the entire dish. The addition of nuts provides a wonderful crunch. The presentation is Instagram-worthy, and the taste lives up to the appearance. A must-try for brunch enthusiasts!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_4",
    restaurant: "Respublica Sadu",
    name: "Coconut Pancakes",
    rating: 4.3,
    description:
      "Delicate coconut-crusted cheese pancakes served with premium ice cream and fresh berries. A perfect balance of warm and cold textures with a refreshing citrus twist.",
    weight: "310 g",
    price: 265,
    ingredients: [
      "coconut-crusted cheese pancakes",
      "ice cream",
      "berries",
      "lemon gel",
      "zest",
      "coconut sugar",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833065/opyjgfaf4xvmedrn0w0f.jpg",
    allergens: ["milk", "eggs"],
    nutrition: {
      calories: 710,
      protein: 24,
      fat: 38,
      carbs: 60,
    },
    reviews: [
      {
        username: "Sophie Williams",
        rating: 4.8,
        text: "These Cheese Pancakes with Ice Cream are simply divine! The coconut crust adds an unexpected tropical twist that works beautifully. The contrast between the warm, fluffy pancakes and the cold, creamy ice cream is perfect. The fresh berries and lemon gel provide a lovely tartness that cuts through the richness. It's like having dessert for breakfast, but somehow it feels perfectly acceptable!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "James Miller",
        rating: 4.6,
        text: "What a delightful dessert experience! The texture of the pancakes is spot-on - crispy on the outside thanks to the coconut crust, yet tender and cheesy on the inside. The ice cream melts slightly, creating a heavenly sauce. The berries are always fresh and the lemon gel adds a sophisticated touch. Worth every calorie!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lily Chen",
        rating: 4.7,
        text: "This is my go-to treat when I want to indulge! The combination of warm cheese pancakes and cold ice cream creates an amazing temperature contrast. The coconut crust is genius - it adds both texture and a subtle tropical flavor. The portion size is perfect for sharing, though you might not want to!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_5",
    restaurant: "Maioran",
    name: "Borscht with Chicken Phyllo",
    rating: 4.6,
    description:
      "Traditional Ukrainian borscht with a modern twist, served with crispy chicken phyllo. A perfect combination of rich flavors and textures in a convenient format.",
    weight: "200/55 g",
    price: 125,
    ingredients: ["borscht with sour cream", "chicken phyllo"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833014/wfb2p177tfk8zp9zfras.jpg",
    allergens: ["milk", "gluten", "eggs (possibly in phyllo)"],
    nutrition: {
      calories: 370,
      protein: 15,
      fat: 20,
      carbs: 30,
    },
    reviews: [
      {
        username: "Viktor Kovacs",
        rating: 3.0,
        text: "The concept of Drinkable Borscht is quite innovative! The traditional flavors are there, but the modern presentation takes some getting used to. The chicken phyllo is a nice accompaniment, adding a necessary crunch to the experience. The portion size could be more generous, but the flavors are authentic. An interesting twist on a classic Ukrainian dish.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Anna Petrova",
        rating: 3.5,
        text: "As someone who grew up with traditional borscht, this drinkable version is intriguing. The flavors are well-balanced and the temperature is perfect. The chicken phyllo adds a nice crispy element that complements the smooth soup. However, I miss the chunky vegetables of the traditional version. It's a good quick lunch option when you're in a hurry.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Michael Roberts",
        rating: 3.1,
        text: "An interesting modern take on borscht! The consistency is perfect for drinking, and the flavors are well-preserved. The chicken phyllo is crispy and flavorful, making a perfect accompaniment. While it's convenient, I feel it loses some of the heartiness of traditional borscht. Good for a quick bite, but might not satisfy if you're really hungry.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_6",
    restaurant: "Maioran",
    name: "Quiche with Broccoli",
    rating: 4.2,
    description:
      "A classic French quiche with a perfect balance of fresh broccoli and spinach. The rich cheese and cream filling creates a luxurious texture in every bite.",
    weight: "190 g",
    price: 130,
    ingredients: [
      "shortcrust pastry",
      "spinach",
      "broccoli",
      "egg",
      "cream",
      "cheese",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833101/ty7mgbriipz0gatqyrox.jpg",
    allergens: ["milk", "eggs", "gluten"],
    nutrition: {
      calories: 430,
      protein: 14,
      fat: 28,
      carbs: 25,
    },
    reviews: [
      {
        username: "Emily Thompson",
        rating: 2.6,
        text: "The Broccoli and Spinach Quiche has potential, but needs some improvement. While the pastry is perfectly crisp and buttery, the filling could use more seasoning. The vegetables are fresh, but the overall taste is a bit bland. The portion size is decent, and it's a healthy option for those looking for a vegetarian meal. Would be better with some additional herbs or cheese.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Thomas Baker",
        rating: 3.0,
        text: "This quiche is a decent vegetarian option. The combination of broccoli and spinach provides good nutrition, and the pastry is well-made. However, the egg mixture could be more creamy, and it definitely needs more cheese. The texture is nice, but the flavor profile could be more complex. A good base that needs some refinement.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sarah Johnson",
        rating: 2.8,
        text: "As a vegetarian, I appreciate the healthy ingredients in this quiche. The shortcrust pastry is well-executed, and the vegetables are clearly fresh. However, it lacks the richness you'd expect from a French quiche. Adding more cream and perhaps some caramelized onions would elevate this dish significantly. The portion size is generous though!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_7",
    restaurant: "Poke LULU",
    name: "Salmon Bowl",
    rating: 4.7,
    description:
      "Fresh gravlax salmon combined with crisp vegetables and creamy chili sauce. A healthy and satisfying bowl that brings the flavors of the ocean to your table.",
    weight: "380/480 g",
    price: 394,
    ingredients: [
      "gravlax salmon",
      "cucumber",
      "avocado",
      "edamame",
      "rice",
      "chili sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833143/moa2eyvd9injrwktdnad.jpg",
    allergens: ["sesame", "fish", "dairy", "soybeans"],
    nutrition: {
      calories: 670,
      protein: 32,
      fat: 35,
      carbs: 45,
    },
    reviews: [
      {
        username: "Ryan Cooper",
        rating: 5.0,
        text: "The Philadelphia Bowl is absolute perfection! The gravlax salmon is cured beautifully, melting in your mouth with each bite. The combination of fresh vegetables provides the perfect crunch, and the avocado adds a creamy richness that ties everything together. The chili cream sauce is a game-changer - just the right amount of heat without overpowering the delicate salmon. This is healthy eating at its finest!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Hannah Kim",
        rating: 4.8,
        text: "This bowl is a masterpiece of balanced flavors and textures! The salmon is consistently fresh and perfectly cured, while the vegetables are crisp and vibrant. The edamame adds a nice protein boost, and the chili cream brings just enough heat to make things interesting. The portion size is generous, making it a satisfying meal that doesn't leave you feeling heavy. Worth every penny!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Daniel Martinez",
        rating: 4.9,
        text: "I can't get enough of this Philadelphia Bowl! The quality of the salmon is outstanding, and the way it's paired with fresh vegetables and creamy avocado is simply perfect. The chili cream adds a subtle kick that elevates all the flavors. The portion size is generous, and the presentation is always beautiful. It's become my go-to healthy lunch option!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_8",
    restaurant: "Poke LULU",
    name: "Beef Bowl",
    rating: 4.4,
    description:
      "Tender teriyaki beef served with roasted baby potatoes and fresh vegetables. A hearty bowl that combines Japanese flavors with Western comfort food.",
    weight: "590 g",
    price: 309,
    ingredients: [
      "teriyaki beef",
      "baby potatoes",
      "mixed vegetables",
      "rice",
      "sesame seeds",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833192/zri1fnbalxnm6lv6f4sk.jpg",
    allergens: ["soy", "mustard", "sesame", "fish", "dairy", "eggs"],
    nutrition: {
      calories: 780,
      protein: 35,
      fat: 38,
      carbs: 60,
    },
    reviews: [
      {
        username: "Oliver Wilson",
        rating: 4.7,
        text: "The Salmon Poke Bowl is a revelation! The fresh sushi-grade salmon literally melts in your mouth. The combination of mango and avocado creates this amazing creamy-sweet contrast, while the edamame and cucumber add the perfect crunch. The ponzu sauce ties everything together beautifully. The portion size is incredibly generous - definitely worth the price!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Maria Garcia",
        rating: 4.5,
        text: "This poke bowl is my healthy addiction! The salmon is always incredibly fresh and cut perfectly. I love how they don't skimp on the avocado, and the mango adds such a lovely tropical sweetness. The rice is consistently well-cooked, and the sesame seeds add a nice nutty flavor. My only suggestion would be to offer a spicier sauce option.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "David Chang",
        rating: 4.6,
        text: "As someone who's had poke in Hawaii, this version really stands up to the authentic experience! The quality of the salmon is outstanding, and the balance of flavors is spot-on. The vegetables are always fresh and crisp, and I appreciate that they don't oversaturate the bowl with sauce. It's a perfect light but filling lunch option.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_9",
    restaurant: "I love kebab",
    name: "Pork Kebab",
    rating: 4.3,
    description:
      "A classic American-style kebab with juicy pork and fresh vegetables. The perfect combination of tender meat and crisp vegetables wrapped in soft lavash.",
    weight: "400 g",
    price: 199,
    ingredients: [
      "lavash",
      "pork",
      "lettuce",
      "tomatoes",
      "onions",
      "special sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833241/ovrbgszdrtymq3cftmrc.jpg",
    allergens: ["eggs", "gluten", "milk (mayonnaise)"],
    nutrition: {
      calories: 820,
      protein: 34,
      fat: 45,
      carbs: 60,
    },
    reviews: [
      {
        username: "Isabella Romano",
        rating: 4.9,
        text: "The Margherita Pizza here is simply outstanding! The crust has that perfect Neapolitan char and chewiness that you'd expect from a high-end pizzeria. The San Marzano tomatoes provide the perfect balance of sweetness and acidity, while the fresh buffalo mozzarella melts beautifully. The fresh basil adds that wonderful aromatic touch. It's as authentic as it gets outside of Naples!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Bennett",
        rating: 4.8,
        text: "This is what pizza should taste like! The simplicity of the Margherita really allows the quality of each ingredient to shine through. The dough has clearly been fermented properly, giving it amazing flavor and texture. The ratio of sauce to cheese is perfect, and I love that they're generous with the basil. A true Italian classic done right!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sofia Martinez",
        rating: 4.7,
        text: "Every bite of this Margherita pizza is a taste of perfection! The crust has that lovely leoparding from the wood-fired oven, and the edge has the perfect amount of puff. The tomato sauce is bright and fresh, and the mozzarella is clearly high-quality. It's simple but executed flawlessly - exactly how a Margherita should be.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_10",
    restaurant: "I love kebab",
    name: "Vegetarian Kebab",
    rating: 4.2,
    description:
      "A vegetarian delight featuring fresh vegetables, mushrooms, and melted cheese in green lavash. A healthy and satisfying option for those who prefer plant-based meals.",
    weight: "360 g",
    price: 169,
    ingredients: [
      "green lavash",
      "tomato",
      "cucumber",
      "mushrooms",
      "cheese",
      "special sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1744833288/romcj7lbhe91ybnwm5jj.jpg",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 670,
      protein: 20,
      fat: 35,
      carbs: 55,
    },
    reviews: [
      {
        username: "Nathan Brooks",
        rating: 4.4,
        text: "The Pepperoni Pizza here hits all the right notes! The pepperoni crisps up perfectly at the edges, and they don't skimp on the toppings. The cheese blend is excellent - stretchy and flavorful without being greasy. The crust has a nice crunch while still maintaining some chewiness. A solid choice for classic pizza lovers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Emma Watson",
        rating: 4.3,
        text: "This is my go-to pepperoni pizza! The sauce has a nice kick to it, and they use quality pepperoni that actually has flavor, not just grease. The crust is consistently well-cooked - crispy on the outside but still soft inside. My only suggestion would be to add an option for extra cheese, as I always want more of their delicious cheese blend!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Marcus Johnson",
        rating: 4.5,
        text: "A fantastic take on the classic pepperoni pizza! The ratio of sauce to cheese is perfect, and the pepperoni is distributed evenly so you get some in every bite. The crust has that lovely wood-fired flavor that adds an extra dimension to the taste. It's large enough to share, but you might not want to!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_11",
    restaurant: "Snack House",
    name: "Chicken Nuggets",
    rating: 4.0,
    description:
      "Crispy golden nuggets made from tender chicken breast with a perfect blend of spices. Served with a special dipping sauce that enhances the natural flavors of the chicken.",
    weight: "250 g",
    price: 100,
    ingredients: ["chicken breast", "breadcrumbs", "spices", "dipping sauce"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201778/dishes/chicken-nuggets.webp",
    allergens: ["gluten", "eggs"],
    nutrition: {
      calories: 320,
      protein: 18,
      fat: 15,
      carbs: 30,
    },
    reviews: [
      {
        username: "Charlotte Davis",
        rating: 1.5,
        text: "The Diavola Pizza was a disappointment this time. While I usually enjoy spicy food, the balance was off - too much heat overwhelmed the other flavors. The crust was slightly undercooked in the middle, and the cheese distribution was uneven. The quality of the spicy salami was good, but the overall execution needs improvement. Hope they can return to their usual standards.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Alex Thompson",
        rating: 1.8,
        text: "I had high hopes for the Diavola Pizza, but it fell short. The spice level was inconsistent - some bites were overwhelmingly hot while others lacked heat entirely. The tomato sauce was a bit too acidic, and the crust was tough rather than crispy. The ingredients seemed fresh, but the composition needs work. Might try something else next time.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Liam O'Connor",
        rating: 1.6,
        text: "Unfortunately, this Diavola Pizza missed the mark. The balance between spicy and savory wasn't quite right, and the crust was too thick in some places. The salami quality was decent, but there wasn't enough cheese to balance the heat. The portion size is good, but the execution needs refinement. Would appreciate more attention to the basics.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_12",
    restaurant: "Pizza Palace",
    name: "Four Cheese Pizza",
    rating: 4.6,
    description:
      "A luxurious combination of four premium cheeses - mozzarella, parmesan, gorgonzola, and edam - on a perfect tomato sauce base. Each cheese brings its unique flavor and texture to create a harmonious taste experience.",
    weight: "450 g",
    price: 240,
    ingredients: [
      "mozzarella",
      "parmesan",
      "gorgonzola",
      "edam",
      "tomato sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201782/dishes/four-cheese.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 800,
      protein: 32,
      fat: 45,
      carbs: 80,
    },
    reviews: [
      {
        username: "Ethan Parker",
        rating: 4.8,
        text: "The Four Cheese Pizza is a cheese lover's dream come true! The blend of mozzarella, gorgonzola, parmesan, and gouda creates an incredibly rich and complex flavor profile. The crust maintains its crispiness despite the generous cheese topping. The drizzle of honey adds an unexpected but delightful sweet note that perfectly balances the sharp cheeses. Absolutely worth the calories!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Julia Chen",
        rating: 4.7,
        text: "This is what cheese pizza should taste like! Each cheese brings its own character - the sharpness of the parmesan, the creaminess of the mozzarella, the boldness of the gorgonzola, and the richness of the gouda. The crust is perfectly thin and crispy, providing an ideal base for all that cheesy goodness. The portion size is generous enough to share, though you might not want to!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Marco Rossi",
        rating: 4.9,
        text: "As an Italian, I'm quite picky about pizza, but this Four Cheese version is exceptional! The balance between the different cheeses is perfect - none overpowers the others. The crust has that authentic wood-fired char that adds depth to the flavor. The addition of fresh herbs on top brings everything together beautifully. A masterpiece of simplicity and quality!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_13",
    restaurant: "Fresh Bar",
    name: "Fresh Orange Juice",
    rating: 4.8,
    description:
      "100% natural orange juice made from freshly squeezed oranges. A refreshing and healthy drink packed with natural vitamins and minerals.",
    weight: "300 ml",
    price: 45,
    ingredients: ["fresh oranges"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201792/dishes/orange-juice.webp",
    allergens: [],
    nutrition: {
      calories: 120,
      protein: 2,
      fat: 0,
      carbs: 28,
    },
    reviews: [
      {
        username: "Sophia Anderson",
        rating: 1.2,
        text: "The Hawaiian Pizza was quite disappointing. The pineapple wasn't fresh and tasted more like it came from a can. The ham was sparse and lacking in flavor. The crust was too thick and doughy in the middle, while the edges were overcooked. The cheese wasn't evenly distributed, and the tomato sauce was too sweet. Really needs improvement in both ingredients and execution.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "William Hughes",
        rating: 1.4,
        text: "As someone who actually enjoys Hawaiian pizza, this version fell short of expectations. The balance between sweet and savory was off - too much pineapple and not enough quality ham. The crust lacked the crispy texture you'd expect from a wood-fired pizza. The cheese quality was mediocre at best. Definitely needs a recipe revision.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Mia Taylor",
        rating: 1.3,
        text: "Unfortunately, this Hawaiian Pizza missed the mark completely. The ingredients seemed low quality - the ham was too salty and the pineapple lacked freshness. The pizza was undercooked, making the crust soggy in the middle. The proportion of toppings was uneven, with some slices overloaded and others nearly bare. Would not recommend or order again.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_14",
    restaurant: "Sushi House",
    name: "Philadelphia Roll",
    rating: 4.7,
    description:
      "A classic sushi roll featuring fresh salmon, creamy cheese, and avocado wrapped in nori. The perfect balance of rich flavors and smooth textures in every bite.",
    weight: "290 g",
    price: 190,
    ingredients: ["salmon", "cream cheese", "avocado", "cucumber", "nori"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201796/dishes/philadelphia.webp",
    allergens: ["fish", "milk", "soy"],
    nutrition: {
      calories: 480,
      protein: 22,
      fat: 28,
      carbs: 42,
    },
    reviews: [
      {
        username: "Noah Martinez",
        rating: 4.9,
        text: "The Meat Lovers pizza is an absolute carnivore's paradise! The combination of pepperoni, bacon, sausage, and ham is perfectly balanced. Each meat is high quality and adds its own distinct flavor. The cheese is perfectly melted and abundant, while the sauce provides just the right amount of tanginess. The crust holds up remarkably well under all those toppings. A must-try for meat enthusiasts!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Isabella White",
        rating: 4.8,
        text: "This pizza is loaded with premium quality meats! The distribution of toppings is generous and even - you get a perfect mix in every bite. The bacon is crispy, the sausage is well-seasoned, and the pepperoni adds that classic pizza spice. Despite being heavy on toppings, the crust remains crispy. The portion size is extremely generous - great value for money!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Brown",
        rating: 4.9,
        text: "Best Meat Lovers pizza I've ever had! The quality of each meat topping is evident - no cheap substitutes here. The way they layer the meats ensures that each one stands out while still working together. The cheese and sauce ratio is perfect, complementing rather than competing with the meats. The crust is sturdy enough to hold everything together. Absolutely worth the splurge!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_15",
    restaurant: "Sushi House",
    name: "Tekka Maki",
    rating: 2.2,
    description:
      "Traditional Japanese tuna roll with perfectly seasoned rice and nori. A simple yet elegant dish that highlights the natural flavors of fresh tuna.",
    weight: "220 g",
    price: 150.0,
    ingredients: ["tuna", "rice", "nori"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201798/dishes/tekka-maki.webp",
    allergens: ["fish", "soy"],
    nutrition: {
      calories: 280,
      protein: 16,
      fat: 4,
      carbs: 50,
    },
    reviews: [
      {
        username: "Ava Wilson",
        rating: 3.5,
        text: "The Vegetarian Pizza offers a decent selection of fresh vegetables. The mushrooms, bell peppers, and onions are well-cooked, and the tomatoes add a nice freshness. However, the overall flavor could be more exciting - perhaps some garlic or herbs would help. The crust is consistently good, and the cheese coverage is adequate. A solid choice for vegetarians, but there's room for improvement.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Oliver Green",
        rating: 3.3,
        text: "As a vegetarian, I appreciate the variety of vegetables on this pizza. The ingredients are fresh and colorful, making for an appealing presentation. However, the vegetables could be better seasoned, and some pieces were slightly undercooked. The sauce is good but could use more herbs to enhance the flavor. The portion size is generous, which is a plus.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Emma Davis",
        rating: 3.4,
        text: "This Vegetarian Pizza has potential but needs some refinement. The vegetable selection is good, and they're clearly fresh, but the overall flavor profile is a bit bland. Adding some roasted garlic or sun-dried tomatoes could really elevate it. The crust is well-made, and the cheese quality is good. It's a healthy option that just needs a little more excitement.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_16",
    restaurant: "Pizza Palace",
    name: "Pepperoni Pizza",
    rating: 4.7,
    description:
      "Classic pepperoni pizza with generous amounts of spicy pepperoni and melted mozzarella. The perfect combination of crispy crust, rich tomato sauce, and aromatic oregano.",
    weight: "430 g",
    price: 210,
    ingredients: ["pepperoni", "mozzarella", "tomato sauce", "oregano"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201795/dishes/pepperoni.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 850,
      protein: 35,
      fat: 42,
      carbs: 76,
    },
    reviews: [
      {
        username: "Benjamin Clark",
        rating: 2.8,
        text: "The BBQ Chicken Pizza has some good elements but falls short in execution. The chicken is tender and well-cooked, but the BBQ sauce is too sweet and overwhelms the other flavors. The red onions add a nice crunch, but there could be more of them. The crust is decent, though it gets a bit soggy in the middle. Would be better with a more balanced sauce and perhaps some additional toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Zoe Thompson",
        rating: 2.6,
        text: "This pizza needs some work. While the concept is good, the BBQ sauce lacks depth - it's all sweetness with no complexity. The chicken pieces are inconsistent in size, leading to some dry bits. The cheese blend is nice, but they could be more generous with it. The crust is well-cooked, but that's not enough to save the overall experience.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Henry Wilson",
        rating: 2.7,
        text: "An average BBQ Chicken Pizza that could be much better. The chicken quality is good, but it needs more seasoning. The BBQ sauce is too dominant and one-dimensional. Adding some cilantro or a drizzle of ranch could help balance the flavors. The portion size is generous, but the quality needs improvement to justify the price.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_17",
    restaurant: "Pizza Palace",
    name: "Diavola Pizza",
    rating: 4.4,
    description:
      "A fiery pizza featuring spicy salami and chili peppers on a bed of melted mozzarella. The perfect choice for those who love bold, spicy flavors.",
    weight: "440 g",
    price: 230,
    ingredients: [
      "spicy salami",
      "chili peppers",
      "mozzarella",
      "tomato sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201781/dishes/diavola.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 820,
      protein: 34,
      fat: 40,
      carbs: 82,
    },
    reviews: [
      {
        username: "Olivia Scott",
        rating: 4.6,
        text: "The Buffalo Chicken Pizza is a spicy masterpiece! The buffalo sauce has the perfect level of heat - enough to make it exciting without overwhelming. The chicken is consistently tender and well-distributed. The blue cheese crumbles add a wonderful tangy contrast, and the ranch drizzle brings everything together. Love the addition of red onions for crunch!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Jackson Lee",
        rating: 4.5,
        text: "This pizza brings the heat in the best way possible! The buffalo sauce is clearly homemade and has great depth of flavor. The chicken is moist and abundant, and I appreciate that they don't skimp on the cheese. The crust stands up well to the saucy toppings without getting soggy. A perfect choice for spice lovers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Madison Taylor",
        rating: 4.7,
        text: "As a buffalo chicken enthusiast, this pizza exceeds expectations! The balance between spicy, tangy, and creamy elements is spot-on. The chicken is always fresh and well-seasoned. The combination of mozzarella and blue cheese is perfect, and the optional ranch on the side is a nice touch. One of my favorite specialty pizzas!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_18",
    restaurant: "Burger Joint",
    name: "Classic Bacon Burger",
    rating: 4.6,
    description:
      "Juicy beef patty topped with crispy bacon, melted cheese, and fresh vegetables. The special sauce adds a unique flavor that makes this burger truly memorable.",
    weight: "320 g",
    price: 170,
    ingredients: [
      "beef patty",
      "bacon",
      "cheese",
      "lettuce",
      "tomato",
      "special sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201771/dishes/bacon.webp",
    allergens: ["milk", "gluten", "eggs"],
    nutrition: {
      calories: 720,
      protein: 38,
      fat: 45,
      carbs: 48,
    },
    reviews: [
      {
        username: "Sebastian Rodriguez",
        rating: 3.8,
        text: "The Mediterranean Pizza offers a nice change from traditional options. The combination of olives, feta, and sun-dried tomatoes brings authentic Mediterranean flavors. The spinach adds freshness, though it could be distributed more evenly. The olive oil drizzle is a nice touch, but sometimes the crust gets a bit too oily. Overall, a good choice for those seeking something different.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Grace Mitchell",
        rating: 3.9,
        text: "A refreshing take on pizza! The feta cheese adds a wonderful saltiness, and the olives are clearly high quality. The artichoke hearts are a great addition, though they could be more generous with them. The herb seasoning is spot-on, really enhancing the Mediterranean theme. The crust is thin and crispy, perfect for these toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Leo Kim",
        rating: 3.7,
        text: "This Mediterranean Pizza has great potential. The ingredients are fresh and authentic, and the combination of flavors is well thought out. However, the distribution of toppings could be more consistent. The crust is good, but sometimes gets soggy from the olive oil. A few adjustments could make this pizza exceptional.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_19",
    restaurant: "Fresh Bar",
    name: "Fresh Lemonade",
    rating: 4.5,
    description:
      "Refreshing homemade lemonade made with fresh lemon juice, mint, and sparkling water. A perfect balance of sweet and tangy flavors with a hint of mint.",
    weight: "400 ml",
    price: 40,
    ingredients: ["lemon juice", "sugar syrup", "mint", "sparkling water"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201788/dishes/lemonade.webp",
    allergens: [],
    nutrition: {
      calories: 80,
      protein: 0,
      fat: 0,
      carbs: 20,
    },
    reviews: [
      {
        username: "Aria Johnson",
        rating: 4.2,
        text: "The Mushroom Truffle Pizza is a fungi lover's delight! The variety of mushrooms used creates a wonderful depth of flavor, and the truffle oil adds that perfect luxurious touch without being overwhelming. The garlic and herbs complement the mushrooms beautifully. The cheese blend is rich and creamy. A sophisticated choice that really delivers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Felix Wong",
        rating: 4.3,
        text: "This pizza is a wonderful celebration of mushrooms! Each variety brings its own unique texture and flavor. The truffle oil is used with restraint, enhancing rather than overpowering the natural mushroom flavors. The thyme and garlic add wonderful aromatic notes. The crust has that perfect wood-fired char that adds to the overall experience.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sophie Martin",
        rating: 4.1,
        text: "A delightfully earthy and aromatic pizza! The combination of different mushrooms creates interesting textures and flavors in each bite. The truffle oil adds luxury without being excessive. The cheese mixture is perfect - creamy but not heavy. Would love to see even more variety in the mushroom selection, but overall it's excellent!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_20",
    restaurant: "Sushi House",
    name: "Rainbow Roll",
    rating: 4.8,
    description:
      "A colorful sushi roll featuring fresh salmon, tuna, and crab stick with avocado and cucumber. The beautiful presentation matches the delicious combination of flavors.",
    weight: "300 g",
    price: 200,
    ingredients: [
      "salmon",
      "tuna",
      "crab stick",
      "avocado",
      "cucumber",
      "rice",
      "nori",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201797/dishes/rainbow.webp",
    allergens: ["fish", "shellfish", "soy"],
    nutrition: {
      calories: 460,
      protein: 24,
      fat: 16,
      carbs: 60,
    },
    reviews: [
      {
        username: "Lucas Foster",
        rating: 3.2,
        text: "The Pesto Chicken Pizza has some good elements but needs refinement. The pesto is fresh and aromatic, though it could use more basil punch. The chicken is tender, but portions are a bit inconsistent. The cherry tomatoes add a nice freshness, but sometimes they make the crust soggy. The mozzarella is good quality, but they could be more generous with it. Decent option if you're looking for something different from traditional pizzas.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Nina Patel",
        rating: 3.4,
        text: "As a pesto lover, I had high hopes for this pizza. The homemade pesto sauce has good flavor, but needs more garlic and pine nuts. The chicken is well-cooked, though some pieces are too small. Love the addition of sun-dried tomatoes, but wish there were more. The crust is consistently good - crispy edges with a chewy center. Has potential but needs some tweaking.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Cameron Wright",
        rating: 3.3,
        text: "This pizza offers an interesting alternative to traditional red sauce bases. The pesto is fresh, though it could be more robust in flavor. The chicken is good quality but needs more seasoning. The mix of fresh and sun-dried tomatoes is clever, adding different layers of flavor. The crust holds up well, but the overall experience could be enhanced with more generous toppings.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_21",
    restaurant: "Burger Joint",
    name: "Guacamole Burger",
    rating: 4.5,
    description:
      "A fresh take on the classic burger with homemade guacamole, fresh vegetables, and melted cheese. The creamy avocado adds a unique texture and flavor to this delicious burger.",
    weight: "340 g",
    price: 160,
    ingredients: [
      "beef patty",
      "guacamole",
      "cheese",
      "lettuce",
      "tomato",
      "onion",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201786/dishes/guacamole.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 680,
      protein: 35,
      fat: 42,
      carbs: 45,
    },
    reviews: [
      {
        username: "Isabella Moore",
        rating: 4.7,
        text: "The Spinach and Goat Cheese Pizza is a vegetarian masterpiece! The combination of creamy goat cheese and fresh spinach is perfectly balanced. The caramelized onions add wonderful sweetness, while the garlic oil base brings everything together. The crust is thin and crispy, holding up well to the toppings. A sophisticated and delicious choice!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Ethan Brooks",
        rating: 4.6,
        text: "This pizza proves that vegetarian options can be incredibly satisfying! The goat cheese adds a tangy creaminess that pairs beautifully with the wilted spinach. The addition of roasted garlic takes it to another level. The drizzle of olive oil at the end adds a lovely richness. One of the best white pizzas I've had!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sophia Lee",
        rating: 4.8,
        text: "An absolutely delightful combination of flavors! The goat cheese is generous and high quality, the spinach is fresh and abundant, and the caramelized onions add the perfect touch of sweetness. The garlic oil base instead of traditional tomato sauce is a brilliant choice. The crust has that perfect wood-fired char. Simply outstanding!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_22",
    restaurant: "Burger Joint",
    name: "Double Cheese Burger",
    rating: 4.7,
    description:
      "Double the pleasure with two juicy beef patties, double cheese, and crispy bacon. A hearty burger that satisfies even the biggest appetites.",
    weight: "420 g",
    price: 180,
    ingredients: [
      "two beef patties",
      "cheese",
      "bacon",
      "lettuce",
      "tomato",
      "special sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201782/dishes/double.webp",
    allergens: ["milk", "gluten", "eggs"],
    nutrition: {
      calories: 920,
      protein: 56,
      fat: 58,
      carbs: 52,
    },
    reviews: [
      {
        username: "Max Turner",
        rating: 2.4,
        text: "The White Pizza needs some work. While the ricotta is creamy and fresh, the overall flavor profile is too bland. The garlic oil base could be more pronounced, and the mozzarella distribution is uneven. The crust is well-cooked, but the toppings need more seasoning and perhaps some additional elements like caramelized onions or herbs to add interest.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Emma Phillips",
        rating: 2.2,
        text: "Unfortunately, this White Pizza falls short of expectations. The combination of cheeses is good in theory, but the execution lacks flavor depth. The garlic is barely noticeable, and the whole pizza needs more seasoning. The crust is decent, but that's not enough to save it. Would benefit from some roasted garlic or fresh herbs to elevate the taste.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Alexander Kim",
        rating: 2.3,
        text: "A rather disappointing experience with the White Pizza. The cheese blend is okay, but there's not enough flavor contrast. The garlic oil base is too subtle, and the whole pizza feels one-dimensional. The texture is good, thanks to the well-cooked crust, but the toppings need serious revision. Some red pepper flakes or fresh basil could help tremendously.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_23",
    restaurant: "Sushi House",
    name: "California Roll",
    rating: 4.6,
    description:
      "A popular sushi roll featuring crab meat, creamy avocado, and crisp cucumber. The addition of tobiko adds a delightful crunch and burst of flavor.",
    weight: "280 g",
    price: 160,
    ingredients: ["crab meat", "avocado", "cucumber", "tobiko", "rice", "nori"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201775/dishes/california.webp",
    allergens: ["shellfish", "fish eggs", "soy"],
    nutrition: {
      calories: 400,
      protein: 18,
      fat: 12,
      carbs: 58,
    },
    reviews: [
      {
        username: "Victoria Chang",
        rating: 4.5,
        text: "The Fig and Prosciutto Pizza is an absolute delight! The sweet figs pair perfectly with the salty prosciutto, creating an amazing flavor balance. The arugula adds a peppery freshness, and the balsamic glaze brings everything together beautifully. The crust is thin and crispy - perfect for these premium toppings. A sophisticated and well-executed combination!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "James Wilson",
        rating: 4.4,
        text: "This pizza is a wonderful blend of sweet and savory! The figs are perfectly ripe and generous, while the prosciutto is sliced paper-thin and of excellent quality. The addition of fresh arugula and a light drizzle of honey makes each bite interesting. The crust provides the perfect canvas for these high-end ingredients. A must-try for adventurous pizza lovers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Luna Martinez",
        rating: 4.6,
        text: "An innovative and delicious combination! The contrast between the sweet figs and salty prosciutto is executed perfectly. The arugula adds a nice peppery bite and freshness. The balsamic reduction is applied with just the right touch - not too much, not too little. The crust has that perfect wood-fired char that elevates the whole experience.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_24",
    restaurant: "Fresh Bar",
    name: "Raspberry Fizz",
    rating: 4.4,
    description:
      "A refreshing blend of natural raspberry juice with sparkling water and fresh mint. The perfect balance of sweet and tart flavors with a hint of minty freshness.",
    weight: "300 ml",
    price: 35,
    ingredients: ["raspberry juice", "sparkling water", "mint"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201798/dishes/raspberry.webp",
    allergens: [],
    nutrition: {
      calories: 90,
      protein: 1,
      fat: 0,
      carbs: 22,
    },
    reviews: [
      {
        username: "Oliver Smith",
        rating: 3.7,
        text: "The Shrimp Scampi Pizza is an interesting fusion concept. The shrimp are well-cooked and generously sized, and the garlic butter sauce is flavorful without being overwhelming. The lemon zest adds a nice brightness, though it could use a bit more. The parsley adds freshness, but sometimes the pizza can be a bit dry. A good option for seafood lovers looking for something different.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Ava Rodriguez",
        rating: 3.8,
        text: "This pizza brings the classic shrimp scampi flavors to a pizza format quite well. The shrimp are fresh and properly cooked, and the garlic butter base is rich and satisfying. Could use a bit more cheese to bind everything together, and perhaps some red pepper flakes for heat. The crust is consistently good - crispy yet chewy.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Mason Lee",
        rating: 3.6,
        text: "A creative take on both pizza and shrimp scampi! The garlic and butter flavors are prominent, and the shrimp are good quality. The addition of fresh herbs is nice, but it needs something more to elevate it - maybe some caramelized onions or a drizzle of quality olive oil. The portion size is generous, and the crust holds up well to the toppings.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_25",
    restaurant: "Fresh Bar",
    name: "Strawberry Fizz",
    rating: 4.3,
    description:
      "Sweet and refreshing strawberry juice mixed with sparkling water and fresh mint. A perfect summer drink that combines natural sweetness with a refreshing fizz.",
    weight: "300 ml",
    price: 35,
    ingredients: ["strawberry juice", "sparkling water", "mint"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201800/dishes/strawberry.webp",
    allergens: [],
    nutrition: {
      calories: 85,
      protein: 1,
      fat: 0,
      carbs: 20,
    },
    reviews: [
      {
        username: "Liam Anderson",
        rating: 4.3,
        text: "The Eggplant Parmesan Pizza successfully combines two Italian classics! The eggplant is perfectly breaded and crispy, not greasy at all. The marinara sauce has great flavor, and the blend of cheeses is spot-on. The basil adds freshness and aroma. Love how they manage to keep the crust crispy despite the substantial toppings. A vegetarian option that doesn't feel like a compromise!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sofia Garcia",
        rating: 4.4,
        text: "This pizza is a clever twist on eggplant parm! The eggplant is sliced thin and cooked perfectly - crispy edges but tender inside. The sauce has a nice balance of herbs and acidity, and they're generous with the cheese. The garlic oil drizzle adds an extra layer of flavor. Really appreciate how each slice has an even distribution of toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Noah Mitchell",
        rating: 4.2,
        text: "A delicious vegetarian option that delivers on flavor! The eggplant is well-seasoned and maintains its texture, while the sauce has a perfect balance of sweetness and acidity. The mix of mozzarella and parmesan adds great depth of flavor. The crust is thin and crispy, providing a perfect base for the hearty toppings. Would definitely order again!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_26",
    restaurant: "Pizza Palace",
    name: "Meat Lovers Pizza",
    rating: 4.7,
    description:
      "A carnivore's dream pizza loaded with pepperoni, bacon, ham, and sausage. Every bite is packed with rich, meaty flavors and melted mozzarella.",
    weight: "500 g",
    price: 250,
    ingredients: [
      "pepperoni",
      "bacon",
      "ham",
      "sausage",
      "mozzarella",
      "tomato sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201790/dishes/meatlovers.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 980,
      protein: 48,
      fat: 52,
      carbs: 84,
    },
    reviews: [
      {
        username: "Emma Thompson",
        rating: 1.8,
        text: "The Anchovy Pizza was quite disappointing. The anchovies were too salty and overwhelmed all other flavors. The distribution was uneven, making some bites inedible while others had no flavor at all. The olive oil base could have been good, but it made the crust soggy. The capers added even more salt to an already over-salted pizza. Needs serious rebalancing.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Brown",
        rating: 1.6,
        text: "As someone who usually enjoys anchovies, this pizza was a letdown. The quality of the anchovies seemed poor - they were too fishy and excessively salty. The crust couldn't hold up to the oil from the fish, resulting in a soggy mess. The garlic was barely noticeable, and the whole pizza lacked balance. Would not recommend in its current form.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Isabella Clark",
        rating: 1.7,
        text: "Unfortunately, this Anchovy Pizza misses the mark completely. The anchovies dominate every bite with their overwhelming saltiness. The tomato sauce is too acidic, creating an unpleasant combination with the fish. The cheese is sparse and unevenly melted. The concept could work with better quality ingredients and more balanced proportions.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_27",
    restaurant: "Pizza Palace",
    name: "Hawaiian Pizza",
    rating: 4.2,
    description:
      "A controversial yet delicious combination of sweet pineapple and savory ham on a bed of melted mozzarella. The perfect balance of sweet and salty flavors.",
    weight: "450 g",
    price: 220,
    ingredients: ["ham", "pineapple", "mozzarella", "tomato sauce"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201787/dishes/hawaiian.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 780,
      protein: 32,
      fat: 36,
      carbs: 88,
    },
    reviews: [
      {
        username: "Ethan Davis",
        rating: 4.1,
        text: "The Artichoke and Olive Pizza offers a delightful Mediterranean flavor profile! The artichokes are tender and well-seasoned, while the mix of black and green olives adds complexity. The garlic oil base works perfectly with these toppings, and the fresh mozzarella melts beautifully. The red onions add a nice bite. A sophisticated choice for vegetable lovers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Charlotte Wilson",
        rating: 4.0,
        text: "This pizza has a great combination of briny and savory flavors! The artichokes are clearly high quality, and the olives add the perfect salty punch. The cheese blend is well-chosen, complementing rather than overwhelming the vegetables. The crust has that nice wood-fired char that adds depth to every bite. A solid choice for those who love Mediterranean flavors.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "William Taylor",
        rating: 4.2,
        text: "A wonderfully executed vegetarian option! The balance between the artichokes, olives, and cheese is perfect. The herbs are fresh and abundant, adding aromatic depth to each slice. The garlic oil base ties everything together nicely. Appreciate that they don't skimp on any of the toppings. The crust provides the perfect foundation for these Mediterranean ingredients.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_28",
    restaurant: "Pizza Palace",
    name: "Margherita Pizza",
    rating: 4.5,
    description:
      "The classic Neapolitan pizza featuring fresh tomatoes, mozzarella, and basil. A simple yet perfect combination of flavors that never goes out of style.",
    weight: "400 g",
    price: 200,
    ingredients: [
      "mozzarella",
      "fresh tomatoes",
      "basil",
      "olive oil",
      "tomato sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201789/dishes/margherita.webp",
    allergens: ["milk", "gluten"],
    nutrition: {
      calories: 720,
      protein: 28,
      fat: 32,
      carbs: 82,
    },
    reviews: [
      {
        username: "Benjamin Clark",
        rating: 2.8,
        text: "The BBQ Chicken Pizza has some good elements but falls short in execution. The chicken is tender and well-cooked, but the BBQ sauce is too sweet and overwhelms the other flavors. The red onions add a nice crunch, but there could be more of them. The crust is decent, though it gets a bit soggy in the middle. Would be better with a more balanced sauce and perhaps some additional toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Zoe Thompson",
        rating: 2.6,
        text: "This pizza needs some work. While the concept is good, the BBQ sauce lacks depth - it's all sweetness with no complexity. The chicken pieces are inconsistent in size, leading to some dry bits. The cheese blend is nice, but they could be more generous with it. The crust is well-cooked, but that's not enough to save the overall experience.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Henry Wilson",
        rating: 2.7,
        text: "An average BBQ Chicken Pizza that could be much better. The chicken quality is good, but it needs more seasoning. The BBQ sauce is too dominant and one-dimensional. Adding some cilantro or a drizzle of ranch could help balance the flavors. The portion size is generous, but the quality needs improvement to justify the price.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_29",
    restaurant: "Snack House",
    name: "French Fries",
    rating: 4.4,
    description:
      "Golden crispy fries made from premium potatoes and cooked to perfection. The perfect side dish or snack that's crispy on the outside and fluffy on the inside.",
    weight: "150 g",
    price: 50,
    ingredients: ["potatoes", "vegetable oil", "salt"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201780/dishes/french-fries.webp",
    allergens: [],
    nutrition: {
      calories: 320,
      protein: 4,
      fat: 16,
      carbs: 42,
    },
    reviews: [
      {
        username: "Sophie Martinez",
        rating: 2.5,
        text: "The Sausage and Pepper Pizza needs improvement. While the Italian sausage is flavorful, it's often unevenly distributed. The bell peppers could be roasted longer to bring out more sweetness. The sauce is a bit too watery, making the center of the pizza soggy. The cheese coverage is inconsistent. Has potential but needs better execution.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Jack Wilson",
        rating: 2.3,
        text: "This pizza falls short of expectations. The sausage quality is good, but there isn't enough of it. The peppers are sometimes undercooked, lacking that nice caramelized flavor. The sauce-to-cheese ratio is off, making some bites too dry and others too wet. The crust is decent, but that's not enough to save the overall experience.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Elena Rodriguez",
        rating: 2.4,
        text: "A mediocre attempt at a classic combination. The sausage lacks the spicy kick you'd expect, and the peppers need more seasoning. The cheese blend is okay, but they could be more generous with it. The crust is inconsistent - crispy on some slices, undercooked on others. Would benefit from better quality control and more attention to detail.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_30",
    restaurant: "Snack House",
    name: "Onion Rings",
    rating: 4.3,
    description:
      "Crispy battered onion rings with a perfect golden crust. A delicious appetizer that combines the sweetness of onions with a satisfying crunch.",
    weight: "200 g",
    price: 70,
    ingredients: ["onions", "batter", "vegetable oil", "spices"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201774/dishes/onion-rings.webp",
    allergens: ["gluten"],
    nutrition: {
      calories: 340,
      protein: 6,
      fat: 18,
      carbs: 40,
    },
    reviews: [
      {
        username: "Benjamin Moore",
        rating: 4.7,
        text: "The Spicy Salami Pizza is a heat lover's dream! The salami is high quality with the perfect amount of spice that builds with each bite. The fresh mozzarella helps balance the heat, and the honey drizzle adds a brilliant sweet contrast. The red pepper flakes and hot oil give you the option to customize your heat level. The crust is perfectly charred - absolutely fantastic!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Olivia Chen",
        rating: 4.6,
        text: "This pizza brings the perfect level of heat! The salami is sliced thin and distributed generously, creating a nice spicy flavor in every bite. The tomato sauce has its own subtle kick, and the basil adds a fresh note that cuts through the richness. Love that they don't shy away from the spice while maintaining the balance of flavors.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Thompson",
        rating: 4.8,
        text: "An outstanding spicy pizza that doesn't sacrifice flavor for heat! The salami is clearly high quality with a complex spice profile. The cheese blend is perfect - enough to cool things down but not drown out the other flavors. The optional chili oil on the side lets you control the heat level. The crust has that perfect wood-fired texture. A must-try for spice enthusiasts!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_31",
    restaurant: "Fresh Bar",
    name: "Cherry Fizz",
    rating: 4.2,
    description:
      "A refreshing cherry juice blend with sparkling water and fresh mint. The natural sweetness of cherries combined with a hint of mint creates a perfect summer drink.",
    weight: "300 ml",
    price: 35,
    ingredients: ["cherry juice", "sparkling water", "mint"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201776/dishes/cherry.webp",
    allergens: [],
    nutrition: {
      calories: 95,
      protein: 1,
      fat: 0,
      carbs: 23,
    },
    reviews: [
      {
        username: "Ava Williams",
        rating: 3.5,
        text: "The Ricotta and Honey Pizza is an interesting sweet-savory combination. The ricotta is fresh and creamy, and the honey adds a nice sweetness, though sometimes it can be a bit too much. The fresh thyme is a clever addition that helps balance the flavors. The crust is well-made, but can get soggy if the ricotta isn't strained properly. A unique option worth trying.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Henry Davis",
        rating: 3.6,
        text: "This pizza offers an unusual but pleasant flavor profile. The ricotta is smooth and well-seasoned, though it could use a bit more salt to contrast with the honey. The addition of cracked black pepper is brilliant. The crust maintains its crispiness well. Would love to see some toasted pine nuts or walnuts added for texture contrast.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Grace Taylor",
        rating: 3.4,
        text: "A creative take on pizza that mostly succeeds. The quality of the ricotta is excellent, and the honey drizzle adds an interesting sweetness. The herbs are well-chosen and fresh. However, the balance can be tricky - some bites are too sweet, others too plain. Adding some caramelized onions or fig jam could make this pizza even better.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_32",
    restaurant: "Sushi House",
    name: "Spider Roll",
    rating: 4.7,
    description:
      "A unique sushi roll featuring crispy soft shell crab with avocado and cucumber. The spicy mayo and tobiko add extra layers of flavor and texture.",
    weight: "320 g",
    price: 180,
    ingredients: [
      "soft shell crab",
      "avocado",
      "cucumber",
      "spicy mayo",
      "tobiko",
      "rice",
      "nori",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201799/dishes/spider.webp",
    allergens: ["shellfish", "eggs", "soy"],
    nutrition: {
      calories: 500,
      protein: 22,
      fat: 24,
      carbs: 56,
    },
    reviews: [
      {
        username: "Leo Parker",
        rating: 4.4,
        text: "The Caramelized Onion and Gorgonzola Pizza is a flavor bomb! The onions are perfectly caramelized, bringing a wonderful sweetness that balances the sharp gorgonzola. The addition of fresh thyme and a drizzle of balsamic glaze takes it to another level. The crust has that perfect wood-fired char that adds depth to every bite. A sophisticated choice for cheese lovers!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Maya Wilson",
        rating: 4.5,
        text: "This pizza is a beautiful balance of sweet and savory! The onions are cooked to perfection - soft, sweet, and abundant. The gorgonzola adds just the right amount of tang without overwhelming. The walnuts add a wonderful crunch and nuttiness. The crust is thin and crispy, providing the perfect base for these premium toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Nathan Brooks",
        rating: 4.3,
        text: "An excellent combination of flavors! The caramelized onions are done properly - sweet and jammy, while the gorgonzola provides a perfect sharp contrast. The honey drizzle is a brilliant touch that ties everything together. The crust maintains its structure despite the generous toppings. A must-try for anyone who loves bold flavors!",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_33",
    restaurant: "Fresh Bar",
    name: "Virgin Mojito",
    rating: 4.6,
    description:
      "A refreshing non-alcoholic mojito made with fresh mint, lime, and sparkling water. The perfect balance of sweet, sour, and minty flavors.",
    weight: "400 ml",
    price: 50,
    ingredients: ["mint", "lime", "sugar syrup", "sparkling water"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201791/dishes/mojito.webp",
    allergens: [],
    nutrition: {
      calories: 120,
      protein: 0,
      fat: 0,
      carbs: 30,
    },
    reviews: [
      {
        username: "Emma Davis",
        rating: 1.9,
        text: "The Seafood Pizza unfortunately misses the mark. While the seafood appears fresh, it's overcooked, making the shrimp and calamari rather tough. The garlic white sauce is too thin, causing the crust to become soggy. The distribution of seafood is uneven, and the overall seasoning needs work. The concept is good but the execution needs significant improvement.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Alexander Kim",
        rating: 1.7,
        text: "Disappointing experience with the Seafood Pizza. The mussels were tiny and scarce, the shrimp was overcooked, and the whole pizza lacked proper seasoning. The lemon zest is barely noticeable, and the herbs taste dried out. The crust couldn't hold up to the moisture from the seafood. Would not recommend in its current form.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Isabella Martinez",
        rating: 1.8,
        text: "This pizza needs serious revision. The seafood quality seems okay, but the preparation is poor - everything is overcooked and chewy. The garlic sauce lacks flavor, and there's not enough cheese to bind everything together. The crust becomes soggy quickly. For the price point, this pizza should be much better executed.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_34",
    restaurant: "Burger Joint",
    name: "Classic Burger",
    rating: 4.5,
    description:
      "The perfect classic burger with a juicy beef patty, fresh vegetables, and special sauce. A timeless combination that never disappoints.",
    weight: "300 g",
    price: 140,
    ingredients: [
      "beef patty",
      "cheese",
      "lettuce",
      "tomato",
      "onion",
      "special sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201781/dishes/classic.webp",
    allergens: ["milk", "gluten", "eggs"],
    nutrition: {
      calories: 650,
      protein: 32,
      fat: 38,
      carbs: 45,
    },
    reviews: [
      {
        username: "William Foster",
        rating: 4.0,
        text: "The Potato and Rosemary Pizza is a delightful surprise! The thinly sliced potatoes are cooked perfectly - tender with slightly crispy edges. The fresh rosemary adds wonderful aromatic flavor, and the garlic oil base ties everything together. The mix of mozzarella and parmesan provides the perfect amount of saltiness. A unique and satisfying option!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sofia Anderson",
        rating: 4.1,
        text: "This pizza offers a wonderful comfort food experience! The potatoes are sliced consistently thin and seasoned well. The rosemary is fresh and abundant, providing that lovely herbal aroma. The cheese blend is perfect - not too heavy but enough to create that satisfying stretch. The crust is crispy enough to support the hearty toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Lucas Thompson",
        rating: 3.9,
        text: "A creative take on pizza that works surprisingly well! The potato slices are perfectly cooked and well-seasoned. The rosemary and garlic combination is classic and executed nicely here. Could use a bit more cheese in some spots, but overall the balance of flavors is good. The crust holds up well to the substantial toppings.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_35",
    restaurant: "Italian Corner",
    name: "Bruschetta",
    rating: 4.4,
    description:
      "Classic Italian bruschetta with fresh tomatoes, basil, and garlic on toasted baguette. The perfect appetizer that combines fresh flavors with crispy bread.",
    weight: "180 g",
    price: 80,
    ingredients: ["baguette", "tomatoes", "basil", "garlic", "olive oil"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201772/dishes/bruschetta.webp",
    allergens: ["gluten"],
    nutrition: {
      calories: 220,
      protein: 6,
      fat: 8,
      carbs: 32,
    },
    reviews: [
      {
        username: "Emma Wilson",
        rating: 1.2,
        text: "На жаль, брускетта не виправдала очікувань. Хліб був пересмажений і надто твердий, а томати виявились водянистими та несмачними. Часник занадто домінував у смаку, перебиваючи всі інгредієнти. Оливкова олія була низької якості, що зіпсувало загальне враження. Порція також виявилась меншою, ніж очікувалось.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Daniel Martinez",
        rating: 1.4,
        text: "Брускетта потребує серйозного покращення. Багет був нерівномірно підсмажений - деякі шматочки горілі, інші недосмажені. Томати були нарізані занадто грубо і не мали достатньо приправ. Базилік виглядав зів'ялим, а часник був перепалений, що надало гіркого присмаку. За таку ціну якість має бути набагато кращою.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sofia Chen",
        rating: 1.3,
        text: "Розчарована цією брускеттою. Як людина, яка часто буває в Італії, можу сказати, що це дуже далеко від автентичного смаку. Інгредієнти здаються низькоякісними - томати безсмакові, оливкова олія з неприємним присмаком, а хліб надто сухий. Співвідношення інгредієнтів також порушене - забагато часнику і замало свіжого базиліку.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_36",
    restaurant: "Burger Joint",
    name: "Chicken Burger",
    rating: 4.3,
    description:
      "A lighter alternative featuring a juicy chicken breast patty with fresh vegetables. The perfect choice for those who prefer poultry over beef.",
    weight: "280 g",
    price: 160,
    ingredients: ["chicken breast", "lettuce", "tomato", "mayo", "pickles"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201778/dishes/chicken.webp",
    allergens: ["gluten", "eggs"],
    nutrition: {
      calories: 580,
      protein: 34,
      fat: 28,
      carbs: 42,
    },
    reviews: [
      {
        username: "Noah Clark",
        rating: 2.8,
        text: "The Breakfast Pizza is an interesting concept but needs work. The eggs are sometimes overcooked, and the bacon could be crispier. The cheese blend is good, and the addition of cherry tomatoes adds nice freshness. The hollandaise sauce is a clever touch but can make the crust soggy. Portion size is generous, but execution needs improvement.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Ava Mitchell",
        rating: 2.7,
        text: "This breakfast-inspired pizza has potential but falls short. The combination of ingredients is promising - eggs, bacon, cheese, and hollandaise - but the execution is inconsistent. The eggs aren't always properly cooked, and the distribution of toppings can be uneven. The crust is good, but the overall experience needs refinement.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "James Wilson",
        rating: 2.9,
        text: "A creative breakfast option that needs some adjustments. The concept is great, but the execution varies. Sometimes the eggs are perfect, other times too done. The bacon needs to be crispier, and the hollandaise sauce could be more evenly distributed. The herbs add nice flavor, but overall consistency needs improvement.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_37",
    restaurant: "Sushi House",
    name: "Dragon Roll",
    rating: 4.8,
    description:
      "An elegant sushi roll with tender eel, creamy avocado, and crisp cucumber. The unagi sauce adds a rich, sweet flavor that complements the ingredients perfectly.",
    weight: "320 g",
    price: 220,
    ingredients: ["eel", "avocado", "cucumber", "unagi sauce", "rice", "nori"],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201783/dishes/dragon.webp",
    allergens: ["fish", "soy"],
    nutrition: {
      calories: 520,
      protein: 24,
      fat: 26,
      carbs: 54,
    },
    reviews: [
      {
        username: "Sophia Rodriguez",
        rating: 4.5,
        text: "The Wild Mushroom Truffle Pizza is absolutely divine! The variety of wild mushrooms creates an incredible depth of flavor, and the truffle oil is used with perfect restraint. The garlic and thyme complement the mushrooms beautifully, while the fontina cheese adds rich creaminess. The crust has that perfect wood-fired char. A mushroom lover's paradise!",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Liam Thompson",
        rating: 4.6,
        text: "This pizza is a fungi enthusiast's dream come true! The selection of wild mushrooms is impressive, each bringing its own unique texture and flavor. The truffle oil enhances without overwhelming, and the herbs are fresh and aromatic. The cheese blend is perfect - creamy but not heavy. The crust provides the ideal canvas for these premium ingredients.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Emma Parker",
        rating: 4.4,
        text: "An outstanding gourmet pizza experience! The mushrooms are clearly high quality and cooked to perfection. The truffle oil adds luxury without being excessive, and the garlic provides just the right punch. The cheese mixture is well-chosen and perfectly melted. Every bite is a delightful combination of earthy flavors.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_38",
    restaurant: "Wings & Beer",
    name: "Buffalo Wings",
    rating: 3.1,
    description:
      "Crispy chicken wings tossed in spicy buffalo sauce with a side of creamy blue cheese dip. The perfect combination of heat and coolness in every bite.",
    weight: "400 g",
    price: 120.0,
    ingredients: [
      "chicken wings",
      "buffalo sauce",
      "butter",
      "spices",
      "blue cheese dip",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201773/dishes/buffalo-wings.webp",
    allergens: ["milk"],
    nutrition: {
      calories: 680,
      protein: 42,
      fat: 52,
      carbs: 8,
    },
    reviews: [
      {
        username: "Oliver Brown",
        rating: 3.7,
        text: "The Spicy Chicken Ranch Pizza offers a good combination of flavors. The chicken is tender and well-seasoned, though the spice level could be more consistent. The ranch drizzle adds nice creaminess, and the red onions provide good crunch. The crust holds up well to the toppings. A solid choice for those who enjoy a bit of heat with their pizza.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Isabella White",
        rating: 3.8,
        text: "This pizza has a nice balance of spicy and creamy elements. The chicken is good quality and generally well-distributed, though some pieces could be more evenly sized. The ranch sauce complements the spicy chicken well, and the addition of fresh tomatoes adds brightness. The cheese blend is generous and melts beautifully.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Mason Davis",
        rating: 3.6,
        text: "A satisfying option for spice enthusiasts! The chicken has good flavor and a decent kick, while the ranch provides necessary cooling. The vegetable toppings are fresh and crisp. Could use a bit more seasoning in some areas, but overall it's a well-executed specialty pizza. The portion size is generous for the price.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_39",
    restaurant: "Burger Joint",
    name: "Vegan Burger",
    rating: 1.6,
    description:
      "A plant-based burger that doesn't compromise on taste, featuring a flavorful patty with vegan cheese and mayo. A delicious option for vegans and meat-lovers alike.",
    weight: "280 g",
    price: 150.0,
    ingredients: [
      "plant-based patty",
      "lettuce",
      "tomato",
      "vegan cheese",
      "vegan mayo",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201803/dishes/vegan.webp",
    allergens: ["soy", "gluten"],
    nutrition: {
      calories: 520,
      protein: 22,
      fat: 24,
      carbs: 58,
    },
    reviews: [
      {
        username: "Mia Anderson",
        rating: 4.2,
        text: "The Sun-Dried Tomato and Pesto Pizza is a delightful Mediterranean-inspired creation! The sun-dried tomatoes add intense flavor and chewy texture, while the pesto base provides wonderful herbal notes. The mozzarella is fresh and creamy, and the pine nuts add a perfect crunch. The crust is thin and crispy - just right for these flavorful toppings.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Ethan Martinez",
        rating: 4.3,
        text: "This pizza offers a wonderful combination of bold flavors! The homemade pesto is fresh and aromatic, and the sun-dried tomatoes add the perfect tangy sweetness. The cheese blend is well-chosen, and the fresh basil on top adds both visual appeal and fresh flavor. The crust has that lovely wood-fired char that enhances every bite.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Sophie Taylor",
        rating: 4.1,
        text: "A fantastic vegetarian option that doesn't skimp on flavor! The pesto base is rich and garlicky, complementing the intense sweetness of the sun-dried tomatoes perfectly. The addition of red onions adds nice sharpness, and the pine nuts provide welcome texture contrast. The portion size is generous, and the ingredients are clearly high quality.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
  {
    id: "dish_40",
    restaurant: "Snack House",
    name: "Mozzarella Sticks",
    rating: 3.8,
    description:
      "Golden-fried mozzarella sticks with a crispy breadcrumb coating and melted cheese center. Served with tangy marinara sauce for the perfect dipping experience.",
    weight: "200 g",
    price: 90.0,
    ingredients: [
      "mozzarella cheese",
      "breadcrumbs",
      "herbs",
      "marinara sauce",
    ],
    image:
      "https://res.cloudinary.com/dlistrvqm/image/upload/v1741201779/dishes/mozzarella-sticks.webp",
    allergens: ["milk", "gluten", "eggs"],
    nutrition: {
      calories: 420,
      protein: 18,
      fat: 28,
      carbs: 32,
    },
    reviews: [
      {
        username: "Lucas Moore",
        rating: 3.4,
        text: "The Greek Pizza offers a nice Mediterranean twist. The feta cheese adds good saltiness, and the olives are high quality. The red onions and bell peppers provide fresh crunch, though they could be more evenly distributed. The oregano adds authentic flavor, but sometimes the overall seasoning can be inconsistent. A decent option for those seeking something different.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "Ava Johnson",
        rating: 3.5,
        text: "This Greek-inspired pizza has good elements but needs some fine-tuning. The combination of feta and olives works well, and the tzatziki drizzle is a clever touch. The vegetables are fresh, though sometimes the tomatoes can make the crust slightly soggy. The herbs are authentic, but the overall balance of flavors could be more consistent.",
        avatar: "/images/icons/user.png",
      },
      {
        username: "William Lee",
        rating: 3.3,
        text: "A creative take on Greek flavors in pizza form. The feta cheese is good quality and generously portioned, the olives add nice brininess, and the fresh vegetables bring color and texture. Could use more herbs and perhaps some garlic oil to enhance the Mediterranean profile. The crust is well-made but sometimes struggles with the moisture from the toppings.",
        avatar: "/images/icons/user.png",
      },
    ],
  },
];
