import Image from "next/image";

const LongTrace = () => {
  return (
    <div className="animate-infinite-scroll-vertical-long flex flex-col gap-[100px]">
      <div className="flex flex-col gap-[100px]">
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/right-trace.png"
          alt=""
          width={130}
          height={300}
        />
        <Image
          src="/images/bg-items/left-trace.png"
          alt=""
          width={130}
          height={300}
        />
      </div>
    </div>
  );
};

export default LongTrace;
